#!/usr/bin/env bash

# Configure MinIO client with default information
mcli config host add mammograms http://localhost:9000 minioadmin minioadmin

mcli mv --recursive $(pwd)/cases mammograms

echo "Done!"

