#!/usr/bin/env bash
git clone https://github.com/sanchezcarlosjr/breast-cancer-pipeline.git
cd breast-cancer-pipeline
virtualenv env --python=python3.10.9
source env/bin/activate
pip install -r requirements.txt
