#!/usr/bin/env bash
git clone https://github.com/sanchezcarlosjr/breast-cancer-pipeline.git
virtualenv env --python=python3.10.9
source env/bin/activate
pip install -r requirements.txt
curl $1 > .env
